# .github/workflows/update-submodules.yml
name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.COMMON_TOKEN }}
          submodules: recursive

      - name: Update submodules
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git submodule update --remote --merge
          git diff --quiet && git diff --staged --quiet && echo "Nothing to update" && exit 0
          git commit -am "chore: update submodules"
          git push
